### ISSUE TITLE
certstore: certstore_windows.go type error

### ISSUE THREAD

**Issue by chkp-idoza** [github/smimesign#107]
After installing & importing the smimesign/certstore package, I get the following error while running my go main program:

..\..\go\pkg\mod\github.com\github\smimesign@v0.2.0\certstore\certstore_windows.go:640:29: cannot convert cmsg (variable of type *_Ctype_char) to type _Ctype_HANDLE

the only code I have added is the following:

	store, err := certstore.Open()
	if err != nil {
		fmt.Println(err)
	}
	defer store.Close()

Is there a way to fix this ?

**Comment by hangorn** [comment]
The same is happening to me

**Comment by ElMostafaIdrassi** [comment]
Should be fixed by #114

**Comment by vcsjones** [comment]
This has been fixed in `main`.
