### ISSUE TITLE
ListKeys fails with Certificate Parsing Failed

### ISSUE THREAD

**Issue by ridomin** [github/smimesign#19]
I'm not able to list all my installed keys, the command `--list-keys` fails with:

```
failed to get identity certificate: certificate parsing failed: asn1: syntax error: PrintableString contains invalid character
```
How can I find the offending certificate?

**Comment by mastahyeti** [comment]
Sorry to hear that. I'm not sure how you could find the offending certificate, but smimesign shouldn't totally fail because of a single wonky cert. I'll work on a fix for that behavior.

**Comment by mastahyeti** [comment]
Would you please confirm that this is fixed in [v0.0.2](https://github.com/github/smimesign/releases/tag/0.0.2)? Maybe being able to list the valid certs will help to find the invalid one by elimination. I would be curious to learn what is "wrong" with the offending cert.

**Comment by ridomin** [comment]
Confirmed the tool does not fail and shows the rest of certificates after the warning. However, I'm not sure what was wrong with the certificate, is it displayed (before or after the Warning)? or just omitted?

**Comment by mastahyeti** [comment]
It will just be omitted now.
