### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by lazyc0derx** [github/smimesign#22]
I have my gpg2 key created for signing commits on git, I need to know that what's the point in using smimesign? PS:- i Know this is protective way of storing keys I want to Know how can I create x.509 keys ? And sign my commits with it and it's handy?
After generating a x.509 key than I have to copy it in which directory in my machine so that git can detect it?, Or after this all I need only x.509 not my old gpg keys? 
Suggest me a way to do this! (like: gpgsm, gnup)
PS:- give full steps to do this!

**Comment by mastahyeti** [comment]
> I have my gpg2 key created for signing commits on git, I need to know that what's the point in using smimesign?

The point of using S/MIME instead of GnuPG is that many organizations already leverage PKI and don't use PGP.

> PS:- i Know this is protective way of storing keys I want to Know how can I create x.509 keys ?

After generating a keypair, you would need to generate a certificate signing request and send it to a public certificate authority. They would then send you a certificate.
