### ISSUE TITLE
Linux install (WSL)

### ISSUE THREAD

**Issue by nowox** [github/smimesign#30]
When I run the install command I get this output: 

```
$ go get github.com/github/smimesign
# github.com/github/smimesign/vendor/github.com/mastahyeti/certstore
src/github.com/github/smimesign/vendor/github.com/mastahyeti/certstore/certstore.go:17: undefined: openStore
# github.com/github/smimesign/vendor/github.com/mastahyeti/cms
src/github.com/github/smimesign/vendor/github.com/mastahyeti/cms/verify.go:151: unknown x509.CertificateInvalidError field 'Detail' in struct literal
```

I have previously installed this on my Ubuntu: 

```
$ sudo apt-get install golang
$ export GOPATH=~
```

How can I fix this?

**Comment by mastahyeti** [comment]
Smimesign is only intended to work on macOS and Windows.

**Comment by nowox** [comment]
I am not quite satisfied with this answer. There is no documentation that indicate this and the error I get should be clearer "You are running on Linux, Smimesign is currently not supported on this platform".

**Comment by mastahyeti** [comment]
The error message you are seeing is from the Go compiler. I'm not aware of any way for a package to control such an error message or to make a platform check be run before Go tries to compile the package. I'm open to suggestions.

**Comment by mastahyeti** [comment]
https://github.com/github/smimesign/pull/31, while hacky, might help make this more obvious to people.
