### ISSUE TITLE
Should I use ID instead of certificate S/N?

### ISSUE THREAD

**Issue by aetos382** [github/smimesign#34]
[The documentation](https://help.github.com/articles/telling-git-about-your-signing-key/#telling-git-about-your-x509-key) is described as:

> 5. From the list of X.509 keys, copy the serial number (S/N) of the X.509 key you'd like to use. In this example, the serial number is a2dfa7e8c9c4d1616f1009c988bb70f:

However, it's incorrect.

When I did that, I could not sign a commit.
When I used ID (thumbprint) instead of S/N, I could sign successfully.

Environments:
> smimesign --version
0.0.6
git --version
git version 2.19.1.windows.1

**Comment by mastahyeti** [comment]
Thanks for opening this. This is a mistake in our documentation. You should be using the ID. I'll open an internal issue about getting this fixed, but will leave this open until that happens.

**Comment by mastahyeti** [comment]
The documentation should be fixed now.
