### ISSUE TITLE
Missing verfication output on Windows

### ISSUE THREAD

**Issue by henning-schild** [github/smimesign#42]
On Linux (using gpgsm) i am used to seeing its output inside the output of `git log --show-signature` or `git tag -v`. With smimesign i do not get such output and can not tell a regular commit from a signed one ... did not try invalid signature.
`git log --pretty="format:%h %G? %aN  %s"` gives me the expected output, so the verification itself is working.
Maybe related to #41 and the output of smimesign going to the wrong fd.

**Comment by henning-schild** [comment]
The output i am talking about looks a bit like what you can find here, https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work 
all the `gpg: ` lines

**Comment by mastahyeti** [comment]
I think the issue is that `smimesign --verify` doesn't produce any output. This should be changed to create output like GPG's.
