### ISSUE TITLE
Make documentation clear about Linux

### ISSUE THREAD

**Issue by Gaeldrin** [github/smimesign#45]
Hello all,

I am aware about both #30 and #31, but not before I actually downloaded the launcher and hit the error message. I suggest to change the README.md to say that Linux is not supported (preferably on top and at Installation section).

I also want to report that [official documentation](https://help.github.com/articles/telling-git-about-your-signing-key/) clearly says that smimesign works on Linux which is obviously wrong. I am aware this is not the best place for issues related to that webpage but I didn't find an easy way to report misleading content there so I hope you can forward this to administrators of that site.

Best regards,
Petr Vsetecka

**Comment by mastahyeti** [comment]
Thanks for opening this. Maybe that documentation could be more clear that this is a macOS/Windows utility. I'm 👎 on documenting every platform that the too _doesn't_ work on though.

**Comment by mastahyeti** [comment]
> I also want to report that official documentation clearly says that smimesign works on Linux which is obviously wrong. I am aware this is not the best place for issues related to that webpage but I didn't find an easy way to report misleading content there so I hope you can forward this to administrators of that site.

Thanks for pointing this out. I've brought this to the attention of the team that maintains our documentation.

**Comment by mastahyeti** [comment]
Our documentation has been updated.

**Comment by Gaeldrin** [comment]
I took another look and I think you did a good job on both ends. :100: Thank you and good luck with future development.
