### ISSUE TITLE
Trying to sign a file using a smartcard and not being asked for password or PIN

### ISSUE THREAD

**Issue by brokenthorn** [github/smimesign#50]
Hi,

`smimesign` looks promising. I was looking for a simple application for macOS to sign files in P7S format. 

```sh
$ smimesign --list-keys
       ID: 7cfe93760af9e1714d5********31bbb96365
      S/N: *****
Algorithm: SHA256-RSA
 Validity: 2018-10-17 15:45:09 +0000 UTC - 2021-10-17 15:45:09 +0000 UTC
   Issuer: CN=certSIGN Qualified CA,O=CERTSIGN SA,C=RO
  Subject: SERIALNUMBER=****,CN=**** *******,O=********,C=RO
   Emails: ******@******.ro
```

It sees my certificate but when I sign, it hangs and nothing happens.

```sh
$ smimesign -s -u 7cfe93760af9e1714d5********31bbb96365 "file.pdf" 
█
```

**Comment by mastahyeti** [comment]
I'm not sure if this is a bug yet, but I think the problem is with how you're invoking the command. Try this for now

```
$ cat file.pdf | smimesign -s -u 7cfe93760af9e1714d5********31bbb96365
```

**Comment by mastahyeti** [comment]
Looks like I never wired this up, as I did with the `--verify` command. I'll open a PR to fix this.

**Comment by brokenthorn** [comment]
> I'm not sure if this is a bug yet, but I think the problem is with how you're invoking the command. Try this for now
> 
> ```
> $ cat file.pdf | smimesign -s -u 7cfe93760af9e1714d5********31bbb96365
> ```

Thanks @mastahyeti, that worked! I have another question before I open a new issue. I need to know if this is OK. Does this app actually have anything to do with S/MIME? Because it seems that it doesn't. It's more like an implementation for https://tools.ietf.org/html/rfc5652 (CMS). Should it be named something like Cryptographic Message Syntax Tool (cmstool)? CMS is used to digitally sign, digest, authenticate, or encrypt arbitrary message content. It replaces PKCS#7. S/MIME thus is built on top of it with special targeting.

**Comment by mastahyeti** [comment]
This tool just does CMS signing. The terms CMS/PKCS#7/S/MIME are all pretty conflated in the common vernacular. Naming this project smimesign doesn't do anything to help that, but I don't have any plans for renaming the project.

**Comment by brokenthorn** [comment]
CMS is supposed to be the new standard that replaces SMIME which has serious security flaws and I think it has been deprecated (yet AV companies say it's still widely used in email clients). Your tool is the only tool I found that is free and works on macOS. Unfortunately, it doesn't produce p7s's that can be validated by my CA. They have a tool called certSIGN Click SIGN but theirs produce different file sizes when signing the same file and they also include all certs in the file (which I've tried with smimesign). My bet is that they use different algorithms or key sizes. Would you be able to compare two versions of a signed file, one with smimesign and one with Click SIGN and determine the difference? And perhaps think about implementing support for obtaining similar results with smimesign? 😅

**Comment by mastahyeti** [comment]
You can compare the signatures using an ASN.1 parser like https://lapo.it/asn1js/.

**Comment by mastahyeti** [comment]
Also, have you tried gpgsm?

**Comment by brokenthorn** [comment]
Thanks for the parser, I didn't know such existed. (I'm not a crypto enthusiast.)
I'll see what the parse outputs and come back if needed.
I'll close this issue now. Thanks for your help.
