### ISSUE TITLE
smimesign --list-keys get nothing

### ISSUE THREAD

**Issue by divinerapier** [github/smimesign#59]
I follow the [github page](https://help.github.com/en/articles/telling-git-about-your-signing-key).
I get nothing when I ran command `smimesign --list-keys`.

**Comment by mastahyeti** [comment]
What operating system are you running? What version of smimesign are you running? Do you have any certificates installed on your computer that can be used for signing?

**Comment by divinerapier** [comment]
hi @mastahyeti 

``` sh
$ echo $SHELL
/bin/zsh
$ smimesign --version
0.0.13
```

The version of my mac is `macOS High Sierra 10.13.4`. I downloaded the gpg from [here](https://gpgtools.org/).   
And then I followed the github 
```
$ history
10888* gpg --full-generate-key
10889* gpg --list-secret-keys --keyid-format LONG
10890* gpg --armor --export 11111111111111111111
10891* gpg --list-secret-keys --keyid-format LONG
10895* git config --local user.signingkey 11111111111111111111
10896* test -r ~/.profile && echo 'export GPG_TTY=$(tty)' >> ~/.profile
10897* echo 'export GPG_TTY=$(tty)' >> ~/.profile
10898* brew install smimesign\n
10899* git config --local gpg.x509.program smimesign
10900* git config --local gpg.format x509
10901* smimesign --list-keys
10902* vim .git/config
10903* git config --local gpg.x509.program smimesign
10904* git config --local gpg.format x509
10905* smimesign --list-keys
10906* brew reinstall smimesign
10907* brew upgrade smimesign
10908* git config --get user.email
10909* smimesign --list-keys
10910* git version
10911* git config --local gpg.x509.program smimesign
10912* git config --local gpg.format x509
10913* vim ~/.gitconfig
10914* git config --local gpg.x509.program smimesign
10915* cat .git/config
10916* vim ~/.gitconfig
10917* vim .git/config
10918* git config --local gpg.x509.program smimesign
10919* git config --local gpg.format x509
10920* smimesign --list-keys
```
Finally, I got nothing.

**Comment by mastahyeti** [comment]
Thanks for the additional information. The smimesign app isn't intended to work with PGP keys. You should use GPG for that. This tool is meant for working with X.509 certificates. This tool will search your macOS keychain (not your GPG keychain) looking for certificates that you have the private key for. The GPG key you generated won't show up in this list.

**Comment by divinerapier** [comment]
Thanks for your help.

**Comment by Karobwe** [comment]
For those who just want to sign their commits but are struggling against this error, follow explanation on the doc then run 
```git config --local --get gpg.x509.program```
If it's say that you are using **smimesign**, change it to **gpg** with 
```git config --local gpg.x509.program gpg```

You can check values used by git with 
```git config --list --show-scope --show-origin```
