### ISSUE TITLE
Register my certificate in github account for getting badge "Verified" on my commits

### ISSUE THREAD

**Issue by mr-tron** [github/smimesign#60]
I made signature with x509 certificate, but I can`t register x509 certificate as GPG key in my account settings, so my commits marked as unverified.
https://github.com/mr-tron/test-sign-x509/commits

**Comment by mastahyeti** [comment]
Was the commit signature created with smimesign? It doesn't look like the signature includes any certificates.

**Comment by mr-tron** [comment]
Sorry. I used gpgsm and it doesn`t add certificates to the sign by default. My error.
