### ISSUE TITLE
Move from Travis CI and Appveyor to GitHub Actions

### ISSUE THREAD

**Issue by lgarron** [github/smimesign#71]
The following files are historical artifacts:

- Travis CI for macOS builds: https://github.com/github/smimesign/blob/main/.travis.yml
- AppVeyor for Windows builds: https://github.com/github/smimesign/blob/main/.appveyor.yml

In fact, the macOS build doesn't upload releases anymore.

Both of these should be moved to GitHub Actions. I have a test branch for macOS at:
https://github.com/github/smimesign/tree/macos-build

This is not a high priority for us, but if someone took the time to migrate and debug the CI files for GH Actions it would help us maintain this project!

**Comment by khmooz** [comment]
#- https://private-639816-snyk.apiary-proxy.com/api/v1/org/4a18d42f-0706-4ad0-b127-24078731fbed/integrations
