### ISSUE TITLE
Custom PKI on GitHub?

### ISSUE THREAD

**Issue by hazcod** [github/smimesign#79]
Hi, perhaps a bit off-topic but I was wondering since the README mentions a private PKI for S/MIME commit signing on git, is this supported on GitHub?

**Comment by vcsjones** [comment]
This is a very late reply, but better late than never :-D.

You can only use a private PKI with GitHub Enterprise Server by adding the root certificate to the trust store of the GHES instance. github.com always uses a fixed trusted store. Users and administrators cannot configure their own root certificates.

Now, there is nothing stopping you from pushing commits to github.com using your own private PKI - they just won't show as "Verified" in the user interface, and likewise any push protection or branch rules requiring signed commits will not permit them.
